// Generated by gencpp from file accept_pkg/xyz.msg
// DO NOT EDIT!


#ifndef ACCEPT_PKG_MESSAGE_XYZ_H
#define ACCEPT_PKG_MESSAGE_XYZ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace accept_pkg
{
template <class ContainerAllocator>
struct xyz_
{
  typedef xyz_<ContainerAllocator> Type;

  xyz_()
    : x(0)
    , y(0)
    , z(0)  {
    }
  xyz_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::accept_pkg::xyz_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accept_pkg::xyz_<ContainerAllocator> const> ConstPtr;

}; // struct xyz_

typedef ::accept_pkg::xyz_<std::allocator<void> > xyz;

typedef boost::shared_ptr< ::accept_pkg::xyz > xyzPtr;
typedef boost::shared_ptr< ::accept_pkg::xyz const> xyzConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::accept_pkg::xyz_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::accept_pkg::xyz_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::accept_pkg::xyz_<ContainerAllocator1> & lhs, const ::accept_pkg::xyz_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::accept_pkg::xyz_<ContainerAllocator1> & lhs, const ::accept_pkg::xyz_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace accept_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::accept_pkg::xyz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::accept_pkg::xyz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accept_pkg::xyz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::accept_pkg::xyz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accept_pkg::xyz_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::accept_pkg::xyz_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::accept_pkg::xyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95da2541c9d6989c0876f480a9b1c7e4";
  }

  static const char* value(const ::accept_pkg::xyz_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95da2541c9d6989cULL;
  static const uint64_t static_value2 = 0x0876f480a9b1c7e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::accept_pkg::xyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "accept_pkg/xyz";
  }

  static const char* value(const ::accept_pkg::xyz_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::accept_pkg::xyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y\n"
"int64 z\n"
;
  }

  static const char* value(const ::accept_pkg::xyz_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::accept_pkg::xyz_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xyz_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accept_pkg::xyz_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::accept_pkg::xyz_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACCEPT_PKG_MESSAGE_XYZ_H
